nix_review/app.py

the temporary file was deleted to early

fix overriding NIXPKGS_CONFIG

---

nix_review/review.py
nix_review/tests/test_app.py

open nix-shell for successful builds

---

.mergify.yml
README.md
nix_review/review.py
nix_review/tests/cli_mocks.py

support running tests

---

nix_review/builddir.py

fixes https://github.com/Mic92/nix-review/issues/47

Append counter in case review directory already exists

---

nix_review/nix.py
nix_review/utils.py
pyproject.toml

Fixes https://github.com/Mic92/nix-review/issues/56

Escape build.nix attributes

---

nix_review/review.py
nix_review/tests/test_pr_borg_eval.py
nix_review/tests/test_pr_local_eval.py
nix_review/tests/test_rev.py
nix_review/tests/test_wip.py

configure parameter should be before the subcommand

fix git fetch command

---

nixpkgs_review/nix.py
nixpkgs_review/tests/cli_mocks.py

Users might have different preferences.
fixes #78

no longer set max-jobs

---

nixpkgs_review/nix/evalAttrs.nix

fix evaluation if python package is marked as broken

---

nixpkgs_review/buildenv.py
nixpkgs_review/review.py

Store path was used from the previous package, which is incorrect.
fixes #96

Fix local evaluation with broken packages

---

nixpkgs_review/report.py
nixpkgs_review/tests/assets/expected_pr_report_1234.md

To make this anunordered list:

report: improve package list format as <ul>

---

default.nix

with this, nixpkgs-review runs in a pure nix-shell

set NIX_SSL_CERT_FILE

---

nixpkgs_review/cli/__init__.py
nixpkgs_review/cli/pr.py

Improve --help messages for some commands and opts

---

README.md

Proofread readme

---

default.nix
nixpkgs_review/nix.py
nixpkgs_review/report.py
nixpkgs_review/review.py
nixpkgs_review/tests/assets/expected_pr_report_1234.md
nixpkgs_review/tests/cli_mocks.py
nixpkgs_review/tests/test_pr_borg_eval.py
nixpkgs_review/tests/test_report.py

Closes #139
I am not sure if we should add 64/32 bit or something else. Open for suggestions.

Add platform run on to report

---

default.nix

fixes https://github.com/Mic92/nixpkgs-review/issues/148

unset PYTHONPATH in executable

---

README.md

Mention required scope for GITHUB_TOKEN

---

README.md
nixpkgs_review/cli/__init__.py
nixpkgs_review/cli/pr.py
nixpkgs_review/cli/rev.py
nixpkgs_review/nix.py
nixpkgs_review/review.py

Closes #182
ToDo:
- update platform run on

Allow to cross compile

---

.mergify.yml
README.md
nixpkgs_review/cli/__init__.py
nixpkgs_review/cli/pr.py
nixpkgs_review/cli/rev.py
nixpkgs_review/nix.py
nixpkgs_review/review.py

This does not work yet when evaluating files

revert 184696e14e (Allow to cross compile)

---

nixpkgs_review/nix.py

Fixes #221
@figsoda Can you test this?

Don't substitute review-shell

---

.gitignore
README.md
default.nix
flake.nix
nixpkgs_review/cli/__init__.py
nixpkgs_review/cli/pr.py
nixpkgs_review/nix.py
nixpkgs_review/review.py
shell.nix
tests/test_pr.py

Fixes https://github.com/Mic92/nixpkgs-review/issues/235.
This PR adds a sandbox based on bubblewrap.
Experimental ~~and lacking tests~~. But I think that opening a PR will allow early feedback.

Add bubblewrap sandbox

---

README.md

Remove : from README.md

---

nixpkgs_review/nix.py

Fix error with wrapQtAppsHook

---

default.nix

@Mic92 or do you have a better idea?

Remove now aliases nixUnstable

---

nixpkgs_review/cli/__init__.py

https://github.com/NixOS/ofborg/pull/588

use ofborg for aarch64-darwin

---

nixpkgs_review/cli/__init__.py
nixpkgs_review/cli/pr.py
nixpkgs_review/nix.py
nixpkgs_review/review.py

also added `--allow-ifd`/`--allow-import-from-derivation` to renable ifd

disable ifd by default

---

.github/workflows/test.yml

this should (hopefully) fix the rate limits

ci: fix typo

---

README.md
nixpkgs_review/cli/__init__.py
nixpkgs_review/cli/pr.py
nixpkgs_review/cli/rev.py
nixpkgs_review/cli/wip.py
nixpkgs_review/review.py

Add --print-result flag

---

default.nix
flake.nix
shell.nix

this will make sure CI runs all the tests

add withNom option and make this the default for devShells

---

nixpkgs_review/review.py

only use ofborg eval when platform is supported

---

nixpkgs_review/nix/evalAttrs.nix

fix detection of broken packages

---

flake.lock
flake.nix

turns out with pure nix is even less code

Drop flake-utils

---

default.nix
nixpkgs_review/cli/__init__.py
pyproject.toml

closes https://github.com/Mic92/nixpkgs-review/issues/294

shell completions with argcomplete

---

nixpkgs_review/builddir.py

This is faster and less code than using python

use git to cleanup worktree

---

nixpkgs_review/cli/__init__.py

```console
$ nixpkgs-review --version
nixpkgs-review 2.10.1
```

add version flag

---

nixpkgs_review/builddir.py
nixpkgs_review/cli/pr.py
nixpkgs_review/errors.py
nixpkgs_review/nix.py
nixpkgs_review/review.py
nixpkgs_review/utils.py

helps to better understand: https://github.com/Mic92/nixpkgs-review/issues/361

print better errors when external commands fail

---

README.md

Minimal version of https://github.com/Mic92/nixpkgs-review/pull/406

doc: mention that only classic PATs work

---

nixpkgs_review/report.py
nixpkgs_review/utils.py

Feat: print skipped packages in yellow in the terminal output

---

.github/workflows/test.yml
default.nix
flake.lock
nixpkgs_review/cli/comments.py
nixpkgs_review/cli/pr.py
treefmt.nix

- **flake.lock: Update**
- **Reformat code base**

flake update

---

nixpkgs_review/cli/__init__.py
nixpkgs_review/cli/pr.py
nixpkgs_review/report.py
nixpkgs_review/review.py

- **introduce the flag --no-headers**
cc @GaetanLepage for the idea

pr: add flag --no-headers

---

nixpkgs_review/github.py
nixpkgs_review/review.py

Fix type error

---

README.md
nixpkgs_review/review.py

Support mixing system aliases and names in the same command

---

pyproject.toml

Release 3.3.0 of nixpkgs-review

Release 3.3.0

---

pyproject.toml

Release 3.4.0 of nixpkgs-review

Release 3.4.0

---

flake.lock
nixpkgs_review/cli/__init__.py
tests/conftest.py

Apply nix fmt to fix formatting issues
This addresses CI failures in PR #517.

Lock file maintenance

---

flake.lock

Follow up to https://github.com/Mic92/nixpkgs-review/pull/544
cc @GaetanLepage @Mic92

fix(deps): fix narHash flake-parts

---

nixpkgs_review/cli/__init__.py
nixpkgs_review/cli/pr.py
nixpkgs_review/report.py
nixpkgs_review/review.py
tests/conftest.py
tests/test_pr.py
tests/test_rev.py
tests/test_wip.py

Resolves #532
https://github.com/Defelo/nixpkgs-review-gha/actions/runs/16851144275
cc @wolfgangwalther

Add --additional-package flag

---

nixpkgs_review/builddir.py
nixpkgs_review/cli/rev.py
nixpkgs_review/cli/wip.py
nixpkgs_review/git.py
nixpkgs_review/review.py
nixpkgs_review/utils.py
pyproject.toml

We need this for git merge. Only tested with tests so far.
Fixes https://github.com/Mic92/nixpkgs-review/issues/410

Always set git author/committer
