Mic92/nixpkgs-review

README.md, nix_review/app.py, nix_review/review.py
Allows to not use ofborg's evaluation result.
Fixes #4.
=> add --eval option

.gitignore, .travis.yml, nix_review/buildenv.py, nix_review/cli.py
Before this check should be performed, the argument parsing should be
fully initialized. This ensures that `nix-review --help` always works,
even if you aren't in `~/nixpkgs`.
=> Run in-nixpkgs check inside commands

README.md, nix_review/cli/__init__.py, nix_review/cli/rev.py, nix_review/cli/wip.py, nix_review/review.py, nix_review/tests/test_wip.py, nix_review/utils.py
This is the only feature that `nox-review` supports and I'm actually
missing here.
Unstaged (or staged changes with `-s`) will be applied onto the git
workspace in `~/.cache/nix-review/rev-{base hash}-dirty` using `git
apply` and tested after that.
=> Implement support for `nix-review wip` to review uncommited changes

nix_review/report.py
`n packages were built` is a simple past passive[1] which consists of a
past form of `to be` and a past participle (which is `built` in this
case).
[1] https://www.grammarbank.com/simple-past-passive.html
=> Fix minor grammar issue in the log

nix_review/builddir.py
If HOME was set, we would just ignore XDG_CACHE_HOME.
=> Respect XDG_CACHE_HOME

nix_review/nix.py
fixes #45
Also if we don't build any packages it is still useful to spawn a nix-shell:
- the pr might only change services a user might want to test
- the ofborg evaluation might not contain proprietary packages
=> always start nix-shell

nix_review/cli/__init__.py, nix_review/review.py
Partially addresses #44 (but doesn't fully support private
repositories).
=> Add `--remote` option to `nix-review rev` for personal forks

nix_review/buildenv.py
It's not necessary to use a function since we don't use the pkgs
attribute. The config can just be an attribute set.
Related to https://github.com/NixOS/nixpkgs/pull/72376#discussion_r341883853
=> buildenv: simplify the config

nixpkgs_review/nix.py, nixpkgs_review/tests/cli_mocks.py
Since we only use disable sandboxes in nixpkgs for packages we need to,
we can just as well switch to relaxed sandboxes.
fixes #75
=> switch to relaxed sandbox

nixpkgs_review/report.py
The verbs were grammatically incorrect whenever the subject was singular: "1 package were built".
The report will now e.g. say "1 package built".
=> report.py: remove verbs to fix grammar

README.md
It took me a minute to figure out why the build failed; this may or may not be
worth including in the readme, but it could help someone.
=> Add note about -I argument for nix-build

README.md, nixpkgs_review/cli/__init__.py, nixpkgs_review/cli/pr.py, nixpkgs_review/report.py, nixpkgs_review/review.py
Add --no-shell arg for non-interactive nixpkgs-review
Usually we want to interactively review, but in some workflows we may want to
use `nixpkgs-review` to batch process a number of PR reviews.
This commit adds a `--no-shell` flag which, when passed, will do everything
except drop into the interactive `nix-shell`, and instead just finish with an
exit code signaling success or failure.
CC @jonringer @mic92
=> Add --no-shell flag for non-interactive nixpkgs-review

nixpkgs_review/report.py, nixpkgs_review/review.py
The list of names is never 0 on this line, so we were always printing a singular
`package` here.
=> Bugfix on plural package(s) printing logic

nixpkgs_review/report.py, nixpkgs_review/tests/assets/expected_pr_report_1234.md, nixpkgs_review/tests/test_report.py
This commit has no functional changes; it merely refactors the
`Report.markdown()` function to be a pure function returning a `str`, so
that we can thread it through to a `request` post in a future update as
part of #89.
Along the way, this adds test coverage to the function to help catch
refactoring bugs, issues like #88, and make the final report output format
easier to view (e.g., can just open the test file to see what it looks like
when reviewing changes to the format).
=> Refactor the report.markdown() function

README.md, default.nix, nixpkgs_review/cli/__init__.py, nixpkgs_review/cli/pr.py, nixpkgs_review/github.py, nixpkgs_review/report.py, nixpkgs_review/review.py, nixpkgs_review/tests/assets/expected_pr_report_1234.md, setup.py
This extends `nixpkgs-review` with a `--comment` flag, active during the `pr`
subcommand, that will post a comment on the PR review with the results.
Resolves #89
CC @mic92 @jonringer @ryantm @fridh
=> Implement --post-result function for PR review comments

nixpkgs_review/builddir.py
I was looking at an old screenshot and noticed that this was spelt incorrectly.
=> Minor spelling correction: Ctlr-C -> Ctrl-C

nixpkgs_review/nix/evalAttrs.nix
Noticed in some PRs that if a package has "meta.broken = true;" it will still be included in the "failed to build" list of packages.
Before:
```
https://github.com/NixOS/nixpkgs/pull/96432
6 packages marked as broken and skipped:
linuxPackages_hardkernel_4_14.zfs linuxPackages_hardkernel_4_14.zfsStable linuxPackages_hardkernel_4_14.zfsUnstable linuxPackages_hardkernel_latest.zfs linuxPackages_hardkernel_latest.zfsStable linuxPackages_hardkernel_latest.zfsUnstable
1 package blacklisted:
tests.nixos-functions.nixosTest-test
13 packages failed to build:
bareos deepin.dde-api deepin.dde-control-center deepin.dde-daemon deepin.dde-dock deepin.dde-file-manager deepin.dde-kwin deepin.dde-launcher deepin.dde-session-ui deepin.deepin-desktop-base deepin.deepin-desktop-schemas …
```
=> Filter out meta.broken = true packages

nixpkgs_review/nix/evalAttrs.nix
still was noticing that a lot of broken packages were still getting picked up.
I did some looking into how ofborg/hydra solve this problem. And there's explicit `checkMeta` config flag that you can pass. Apparently this is respected when building packages, but isn't respected when evaluating (unless it's passed explicitly)
before:
```
https://github.com/NixOS/nixpkgs/pull/98657
44 packages failed to build:
digikam k9copy kmymoney libsForQt5.kdewebkit libsForQt5.kreport libsForQt512.akonadi-calendar libsForQt512.akonadi-contacts libsForQt512.akonadi-import-wizard libsForQt512.akonadi-mime libsForQt512.akonadi-notes libsForQt512.akonadi-search libsForQt512.calendarsupport libsForQt512.eventviews libsForQt512.grantleetheme libsForQt512.incidenceeditor libsForQt512.kalarmcal …
```
=> fix meta check

nixpkgs_review/nix/evalAttrs.nix
This allows for unfree packages to not be marked as "broken or skipped"
closes #134
without changes:
```
[11:30:54] jon@jon-desktop /home/jon/projects/nixpkgs (fix-tabnine)
$ ../nix-review/result/bin/nixpkgs-review pr 99310
$ git -c fetch.prune=false fetch --force https://github.com/NixOS/nixpkgs master:refs/nixpkgs-review/0 pull/99310/head:refs/nixpkgs-review/1
$ git worktree add /home/jon/.cache/nixpkgs-review/pr-99310-5/nixpkgs ebb5b9ab2e38afb58abd4723a407b39198675754
Preparing worktree (detached HEAD ebb5b9ab2e3)
HEAD is now at ebb5b9ab2e3 Merge pull request #99282 from fadenb/systemdjournal2gelf_20200813
$ nix-env -f /home/jon/.cache/nixpkgs-review/pr-99310-5/nixpkgs -qaP --xml --out-path --show-trace
$ git merge --no-commit 211f37819c143d6260d0fba61bfe6ae8863dea51
Updating …
```
=> Allow for unfree packages to be built

nixpkgs_review/report.py, nixpkgs_review/utils.py
I always had trouble finding the link to the currently running review. So I made it blue, clickable and added some whitespace.
Compared to
=> Make the PR link distinct and clickable

flake.lock
a newer version of black is necessary to satisfy checks
fixes #153
=> bump nixpkgs in flake.lock

nixpkgs_review/nix.py
The sandbox does not correctly work on Darwin and hydra does not activate it either.
=> Only activate sandbox on Linux

nixpkgs_review/review.py, nixpkgs_review/tests/test_pr_borg_eval.py, nixpkgs_review/tests/test_pr_local_eval.py, nixpkgs_review/tests/test_rev.py
This fixes the problem with "Not possible to fast-forward..."
in environments where git is configured with `ff = only`
configure git with `ff only`:
```
$ git config merge.ff only
```
And try to run nix-review in cases where fast forward is not an option.
If you have this in global configuration at the moment the easiest way is to reconfigure nixpkgs repository to override this:
```
$ git config merge.ff false
```
This patch should make it so that merge nixpkgs-review is doing is independent of a configuration.
=> Override --ff-only option which might be globally configured

nixpkgs_review/nix.py
While doing ``nixpkgs-review pr 110813`` I got the following error:
```
The store path /nix/store/4q77nsvmv3gg80bg0r43d5m9aiifdxhf-test-writers is a file and can't be merged into an environment using pkgs.buildEnv! at /nix/store/pm3r9b13iwvw2hr7v7b9nwlnssp0i858-builder.pl line 109.
The store path /nix/store/4q77nsvmv3gg80bg0r43d5m9aiifdxhf-test-writers is a file and can't be merged into an environment using pkgs.buildEnv! at /nix/store/pm3r9b13iwvw2hr7v7b9nwlnssp0i858-builder.pl line 109.
builder for '/nix/store/3hp03ih3grhpb1s2cg5gq1bgghwpa2m0-env.drv' failed with exit code 2
error: --- Error ----------------------------------------------------------------------------------------------------------------------------------------------------------------- nix-shellbuild of …
```
=> Blacklist tests.writers

default.nix, nixpkgs_review/report.py
- Fix log files not being collected for already build packages
- Remove usage of stdenv.lib
Before nix log used the drv to collect the log files which are not available after a rebuild.
```
error: --- Error -----------------------------------------------------------------------------------------------------------------------------------------------------------------------
nixbuild log of '/nix/store/g3328kr658gkvc2230dv6ay7gw6ac94j-perl5.32.0-wakeonlan-0.41.drv' is not available
```
Now we just use the path of the build package where we can always collect the log.
I require this to grep logs when doing more than one run of nixpkgs-reviews.
=> Fix log collection for already build packages

default.nix, nixpkgs_review/review.py
As discussed in IRC and the meetup. This change respects meta.broken in review-shells.
=> Unset NIXPKGS_CONFIG to respect meta.broken in review shells

README.md, default.nix, flake.lock, nixpkgs_review/cli/__init__.py, nixpkgs_review/cli/pr.py, nixpkgs_review/nix.py, nixpkgs_review/review.py, tests/assets/nixpkgs/default.nix
Add a `--system` argument, which can be used to evaluate and build packages for systems other than the local one.
It passes down the specified system to nix invocations when evaluating the package set as the `system` option. During evaluation it should not matter if the local nix can actually build packages for the system, as it primarily sets `builtins.currentSystem`. I'm not sure if this is also true for IFD evaluations.
When constructing the nix-shell with the packages to build, it sets the `nixpkgs { system = ...; }` config. This avoids miss-configuring the build environment with a system that can't actually be build locally and allows to use all the configured nix build systems.
=> Add --system argument

nixpkgs_review/nix.py
This recently popped up. Not sure which change introduced it but it does not cause a build failure, it is only a bit annoying.
~~Needs testing.~~
=> Ignore tests.trivial

default.nix, nixpkgs_review/builddir.py, nixpkgs_review/buildenv.py, nixpkgs_review/cli/__init__.py, nixpkgs_review/cli/pr.py, nixpkgs_review/cli/rev.py, nixpkgs_review/cli/wip.py, nixpkgs_review/nix.py, nixpkgs_review/nix/evalAttrs.nix, nixpkgs_review/review.py
While evalling https://github.com/NixOS/nixpkgs/pull/131530 locally I got the following report.json
```
{
"blacklisted": [],
"broken": [],
"built": [
"libjpeg_drop",
"lightworks"
],
"failed": [],
"non-existant": [],
"pr": 131530,
"system": "x86_64-linux",
"tests": []
}
```
libjpeg_drop is an alias to libjpeg_original and because I have aliases disabled it does not work.
=> Don't use aliases when evalling locally

nixpkgs_review/cli/__init__.py
Use a non-capturing group to include `ghp_` prefixes in reading
`oauth_token` from `hub` config, while keeping compatibility with older
tokens (that the user should be refreshing soon.)
cf https://github.blog/2021-04-05-behind-githubs-new-authentication-token-formats/
=> cli/__init__.py: support GitHub's auth token format in oauth_token

nixpkgs_review/review.py
The command to fetch the PR branches is also fetching all reachable tags from those references, but it's not something that it should be expected to do. In one-shot fetchs like that the tags are not relevant, as discussed in the man page of `git tag`.
Add the `--no-tags` flag to disable automatic tag following.
Closes #222.
=> Do not fetch tags when fetching PR branches

README.md, nixpkgs_review/cli/__init__.py
In `~/.config/gh/hosts.yaml` I have:
```yaml
github.com:
user: jyooru
oauth_token: gho_secrettokenhere
git_protocol: ssh
```
nixpkgs-review is already reading this file, but the regex failed to detect my token. This pull request fixes this.
=> fix reading github token from gh config

nixpkgs_review/cli/__init__.py
Before the change re.match was not able to find hub key as
re.match does full string match.
After the change re.search uses substring match to be more
tolerant to yaml syntax.
=> cli: fix 'hub' token reading search

nixpkgs_review/report.py
Currently, only the log of the first derivative is saved and the function returns afterwards. Instead it should break and continue with the next derivation
=> Fix error log generation

nixpkgs_review/cli/__init__.py, nixpkgs_review/cli/pr.py
Ofborg does a check with `allowAliases = false;`. So it's safe to assume that our evaluation shouldn't have to worry about them either.
```
ofborg-eval-package-list-no-aliases — nix-env -qa --json --file . --arg config { allowAliases = false; }
```
related: https://github.com/Mic92/nixpkgs-review/pull/254
=> Disable aliases by default

nixpkgs_review/review.py
The GIT_EXTERNAL_DIFF environment variable can be configured to use a
custom diff tool for interactive diff commands, but it may not produce
an output compatible with `git apply`, so `--no-ext-diff` should be
used to ensure that the diff output is usable for this purpose.
=> Disable external git diff tools when patching

nixpkgs_review/nix.py, tests/assets/nixpkgs/default.nix
without this pr (on nixos):
```console
$ nixpkgs-review rev HEAD --system aarch64-darwin
[...]
$ ls
bash: /nix/store/npcq66nqv2wpzp3ma5s63vafnnivphxb-coreutils-9.1/bin/ls: cannot execute binary file: Exec format error
```
this pr changes so the shell is built with the local system, and the snippet works
=> make --system work better with the shell

nixpkgs_review/nix.py
I ended up trying to build the linux kernel due to darwin.builder, I think it is safe to ignore it
=> ignore darwin.builder

nixpkgs_review/allow.py, nixpkgs_review/buildenv.py, nixpkgs_review/cli/__init__.py, nixpkgs_review/cli/pr.py, nixpkgs_review/cli/rev.py, nixpkgs_review/cli/wip.py, nixpkgs_review/nix.py, nixpkgs_review/review.py
this is the default behavior for ofborg and hydra: https://github.com/NixOS/ofborg/pull/628
also adds `--allow-url-literals`
=> disallow url literals by default

nixpkgs_review/report.py
these packages likely won't have logs, and even if they do, they are not built by nixpkgs-review and wouldn't be helpful
=> skip posting logs of blacklisted packages

nixpkgs_review/nix.py, nixpkgs_review/report.py, nixpkgs_review/review.py, nixpkgs_review/utils.py, tests/conftest.py
otherwise experimental-features configured in nix.conf is overridden
=> treewide: replace --experimental-features with --extra-experimental-features

default.nix, flake.nix, shell.nix
cherry-picked from #296, this makes sure that the bubblewrap tests are ran in ci since the conversion to flakes in #300
=> enable bubblewrap feature in devShell

nixpkgs_review/github.py
pull requests that don't have no rebuilds (like https://github.com/NixOS/nixpkgs/pull/213182) do not have a gist linked to its `ofborg-eval` status
=> use ofborg's results even if there are no rebuilds

README.md, nixpkgs_review/cli/__init__.py, nixpkgs_review/cli/pr.py, nixpkgs_review/nix.py, nixpkgs_review/review.py, nixpkgs_review/utils.py, tests/test_pr.py, tests/test_rev.py, tests/test_wip.py
`nix-output-monitor` provides a nice real time build graph, which gives more information about what builds where, which is especially nice for larger rebuilds.
fixes #302
=> feature: add `--nom` flag to enable nix-output-monitor

nixpkgs_review/nix/evalAttrs.nix
fixes #306
the output paths will be similar to the regular nix `result`s, the following results are tested with https://github.com/NixOS/nixpkgs/pull/215728
```console
4 packages built:
geogram geogram.bin geogram.dev geogram.lib
$ tree results
results
├── geogram -> /nix/store/jd1ys0jn7sp9bw647ch8ydp5ic3l09g6-geogram-1.8.2
├── geogram.bin -> /nix/store/j64i56kvgg5wp5m1snhxwmm9wcbg2zm1-geogram-1.8.2-bin
├── geogram.dev -> /nix/store/cr6wlvc22gj072r0fw0j52kbmqmpr6my-geogram-1.8.2-dev
└── geogram.lib -> /nix/store/299za097p633g4w1ig63g8k5zcf86nk6-geogram-1.8.2-lib
```
=> build and symlink each output of the packages

nixpkgs_review/cli/__init__.py
`--system` cannot be respected when creating the argument parser
=> deduplicate ofborg supported platforms

nixpkgs_review/nix.py
=> fix sandbox

nixpkgs_review/cli/__init__.py
fixes https://github.com/Mic92/nixpkgs-review/issues/332
=> get github token from cli output

nixpkgs_review/report.py
```
warning: The interpretation of store paths arguments ending in `.drv` recently changed. If this command is now failing try again with '...^*'
```
=> avoid `nix log` warning

nixpkgs_review/utils.py, tests/test_escape_attr.py
I found a lexing issue in nix when running nixpkgs-review for https://github.com/NixOS/nixpkgs/pull/247099. 
It generated a line like `haskelPackages.if` and Nix confused it with a if statement.
I also added tests to check compliance.
=> utils/escape_attr: enclose with quotes all elements but the first + tests

nixpkgs_review/builddir.py, nixpkgs_review/cli/post_result.py, nixpkgs_review/nix.py, nixpkgs_review/review.py, tests/test_github_actions.py
Nix does not respect `NIX_PATH` when the `nix-path` setting in nix.conf
is set, which breaks the `nix-store --verify-path` due to `<nixpkgs>`
diverging from the temporary nixpkgs created by nixpkgs-review.
fixes #343
=> don't rely on `NIX_PATH`

nixpkgs_review/nix.py, nixpkgs_review/review.py
fixes this warning
```
warning: Nix search path entry '/tmp/tmpXXXXXXXX' does not exist, ignoring
```
=> allow access to the nixpkgs overlay in the sandbox

nixpkgs_review/report.py
Culprit found with:
```
python -m trace --ignore-dir "$(python -c 'import os, sys; print(os.pathsep.join(sys.path[1:]))')" -t $NIXGITS/nixpkgs-review/result/bin/.nixpkgs-review-wrapped pr 261631
```
from the comments of https://stackoverflow.com/a/33449763.
`nix log` had `None^*` as the path.
Closes https://github.com/Mic92/nixpkgs-review/issues/354
=> fix "error: cannot find flake 'flake:None' in the flake registries"

default.nix, flake.lock, nixpkgs_review/cli/__init__.py, nixpkgs_review/cli/post_result.py, nixpkgs_review/cli/wip.py, nixpkgs_review/nix.py, nixpkgs_review/report.py, nixpkgs_review/review.py, pyproject.toml, tests/conftest.py, tests/test_pr.py, tests/test_wip.py
=> add pylint configuration

nixpkgs_review/builddir.py, nixpkgs_review/cli/__init__.py, nixpkgs_review/errors.py, nixpkgs_review/github.py, nixpkgs_review/review.py, nixpkgs_review/utils.py
fix use-dict-literal
https://pylint.pycqa.org/en/latest/user_guide/messages/refactor/use-dict-literal.html
=> pylint fixes

nixpkgs_review/nix.py, nixpkgs_review/nix/review-shell.nix
Previously, the whole shell.nix was created at runtime using string substitution and other crimes that made it hard to work on the expression itself.
This patch turns the string substitutions into Nix function arguments to an otherwise static Nix expression and only generates the list of attrs to be built dynamically.
=> nix: make review-shell.nix code static

default.nix
Result after this change (zsh, but tested in bash and also makes them work but less nice but also unconfigured bash compared to personal zsh-setup):
I wen the wrong way first and tried to setup/make argcomplete global-setup work with NixOS/wrappers by resolving the last line and redirecting the resolution but later figured out that's not needed.
I looked through nixpkgs and only found one other package using the full path (https://github.com/search?q=repo%3ANixOS%2Fnixpkgs+register-python-argcomplete+%24out&type=code) and enabling `_ARC_DEBUG` made me realize the registered completion does not trigger as it never (except you copy the full path to nix-store) matches.
If this is accepted I can also provide a nixpkgs-pr with reference to here ✌🏻
=> argcomplete: fix auto-generated shell-completions in postInstall

nixpkgs_review/utils.py
[shlex.join](https://docs.python.org/3/library/shlex.html#shlex.join) handle adding ' when argument contains space. Before it was printed like this: `--extra-experimental-features nix-command no-url-literals`
=> print copiable commands

nixpkgs_review/report.py, nixpkgs_review/review.py
This way, `nixpkgs-review pr ... -c commit` will add `--checkout commit` to the markdown report. This is useful when checking against hydra
=> Add checkout strategy to report.

nixpkgs_review/cli/pr.py, nixpkgs_review/review.py
This makes `--no-shell --post-result` with multiple PRs post more than just the first report.
=> Make `--no-shell` not exit early

nixpkgs_review/report.py
Fixes https://github.com/Mic92/nixpkgs-review/issues/404
=> Add emojis to nixpkgs-review post-result

README.md
In late 2022, GitHub [introduced][1] a new type of API tokens that are supposed to be more secure and fine grained than the old type of tokens.  But they won't work for nixpkgs-review's purposes (at least for now) because there is no way to grant these new tokens access to resources that are not owned by you, and most users of nixpkgs-reviews are not owners of @NixOS/nixpkgs which is the repo they're trying to submit pull request comments to (when using `--post-result`, anyway).
This commit clarifies the README instructions so that users will know they need to create the old type of API token, the "personal access token (classic)", and not the new type.
Also did a bit of rewording for further clarity.
[1]: https://github.blog/2022-10-18-introducing-fine-grained-personal-access-tokens-for-g …
=> Update instructions for GitHub API tokens

README.md, nixpkgs_review/cli/__init__.py, nixpkgs_review/cli/pr.py, nixpkgs_review/nix.py, nixpkgs_review/nix/review-shell.nix, nixpkgs_review/report.py, nixpkgs_review/review.py, nixpkgs_review/utils.py, tests/conftest.py, tests/test_pr.py, tests/test_rev.py, tests/test_wip.py
This PR addresses #400 by allowing to evaluate a PR/revision for multiple systems at once.
You can now provide the `--systems` option with a list of systems to evaluate:
- `--systems current` (default): legacy behavior
- `--systems "x86_64-linux aarch64-darwin"`: evaluate for both intel linux and ARM darwin
- `--systems all`: evaluate on all four main platforms
> [!Note]
>
> This is still a WIP. ~~The tool works fine when using ofborg eval but I have not yet adapted to local evaluation.~~
> The code is quite dirty for now and will require more polish ~~once everything will be working~~.
> Also, I am fully open to suggestions regarding the solution and coding style.
I am eager to receive some feedback !
- Basically, adding this feature requires a pretty heavy refactoring.
Every place where …
=> Feat: add support for multi-systems

nixpkgs_review/report.py, nixpkgs_review/review.py, nixpkgs_review/utils.py
The script displays 'Impacted packages' for each system.
This ensures that the systems are enumerated in the canonical order.
=> Sort systems in stdout

nixpkgs_review/cli/__init__.py, nixpkgs_review/cli/pr.py, nixpkgs_review/nix.py, nixpkgs_review/review.py
When ofborg's evaluation results are not available or when the user specifies `--eval local`, local evaluation is used to list packages affected by a PR.
This process is quite time-consuming and could be done in parallel when evaluating for multiple systems.
Ultimately, the performance of [nix-eval-jobs](https://github.com/nix-community/nix-eval-jobs) could be leveraged to perform this task.
Unfortunately, as it is currently, `nix-eval-jobs` cannot be used as a drop-in replacement in this code base.
As an intermediary situation, I suggest to ship a simple parallel solution.
This approach can be very memory-intensive.
Running it with 4 parallel processes (one for each system) consumes approximately 55GB of RAM.
Nonetheless, it unsurprisingly reduces the time spent on evaluation almost …
=> Feat: add basic parallel support for listing packages

README.md
```console
> nixpkgs-review --sandbox pr 361460
usage: /nix/store/lzz1i98h78miinzx3yg6ly7kl4ypxd42-nixpkgs-review-3.0.0/bin/nixpkgs-review
[-h] [--version]
{post-result,approve,comments,merge,pr,rev,wip} ...
/nix/store/lzz1i98h78miinzx3yg6ly7kl4ypxd42-nixpkgs-review-3.0.0/bin/nixpkgs-review: error: unrecognized arguments: --sandbox
> nixpkgs-review pr --sandbox 361460
-> Attempting to fetch eval results from GitHub actions
-> Successfully fetched rebuilds: no local evaluation needed
...
Using sandbox mode. Some things may break!
```
=> fix example CLI flags for the sandbox

nixpkgs_review/review.py
The `self.checkout` test is the wrong way round, so `nix-review rev` always does a `git checkout` and not merge the given commit.
=> Fix Review.build_commit merge behavior

nixpkgs_review/report.py
Small typo fix. Currently the report talks about tests and testss:
```
--------- Report for 'x86_64-linux' ---------
2 testss built:
nixosTests.initrd-network-openvpn nixosTests.systemd-initrd-networkd-openvpn
```
```
--------- Report for 'x86_64-linux' ---------
1 tests built:
nixosTests.initrd-network-openvpn
```
This should take care of that. Haven't run tested it.
=> report: fix test plural reporting

nixpkgs_review/nix.py
This contains (up to) all packages that have a known pkg-config module in their output.
=> Blacklist tests.pkg-config.defaultPkgConfigPackages.tests-combined

nixpkgs_review/review.py
multiple concurrent git fetches could override refs each other. In my experience also not all git operations cope well with concurrency, so I think it's better to just add a big lock around it.
=> add file lock around nixpkg-review

nixpkgs_review/report.py, nixpkgs_review/review.py, nixpkgs_review/utils.py
This is helpful when running with --no-shell where there's no "paused"
context of nix-shell to assume. The link is clickable.
(Yes, the user sees git workspace removed at the end of the run but it's
not very convenient to copy the root of nixpkgs checkout, then append
`logs` manually.)
=> Print out log directory at the end of the run

nixpkgs_review/report.py
=> Make listed built packages into hyperlinks (on tty)

nixpkgs_review/cli/pr.py, nixpkgs_review/report.py, nixpkgs_review/review.py
Sometimes it's hard to say which commit a particular report belongs to,
especially when new commits were pushed while nixpkgs-review was
running. This change will make it explicit.
=> Include commit hash under test in the report

README.md, nixpkgs_review/cli/__init__.py, nixpkgs_review/cli/pr.py, nixpkgs_review/report.py, nixpkgs_review/review.py
Snippets will be hidden under dropdown sections so as not to clutter UI.
Snippets are limited to 20 lines, and if too many logs are generated,
the report is truncated so that it fits into a single github comment.
Related: #308
=> Add tails of logs of failed packages to github comments

nixpkgs_review/report.py
=> fix: Don't append </details> when no logs were added

nixpkgs_review/github.py
This is to support [#415006.](https://github.com/NixOS/nixpkgs/pull/415006).
=> Support new "PR" workflow in nixpkgs

nixpkgs_review/report.py
The commit info is right there anyways, and it'd be useful for me to have it in the JSON format.
=> report.py: add commit to output JSON

README.md, nixpkgs_review/cli/__init__.py
This environment variable can be used to specify a command which should return the token. 
This can for example be globally defined to a public command which would ask a password manager to provide this secret, eg. `pass github-token` / `rbw get github-token`
=> add GITHUB_TOKEN_CMD

nixpkgs_review/report.py
Previously, packages in `nixosTests` have always been added to the `tests` list (which is shown as `:white_check_mark: 1 test built:` in the markdown report), regardless of whether the test succeeded or failed.
This puts all failed packages into the `failed` list and only the tests that succeeded into the `tests` list.
=> Correctly report failed tests as failed

nixpkgs_review/errors.py, nixpkgs_review/github.py
Throw a custom exception when we a get 410 on fetching CI results and handle accordingly in the review process to fallback to local evaluation. 
Closes https://github.com/Mic92/nixpkgs-review/issues/476
Dependent on https://github.com/Mic92/nixpkgs-review/pull/545 for CI, pulled these changes into separate branch so it doesn't hold that one up. 
---------------------------------------------------
Just saw this in the associated issue
> We should treat 410 the same way as 404.
Should i make the exception raised on `404`, as well? My understanding was that 404 waits for a retry loop so that you can wait for an evaluation to finish. But, here we had an evaluation that did finish and we know it won't because it just expired so we just force a local retry.
=> fix(github): handle expired artifacts with custom exception
